name: indo_journal
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - asttokens=2.4.1
  - bzip2=1.0.8
  - ca-certificates=2024.9.24
  - comm=0.2.2
  - debugpy=1.6.7
  - decorator=5.1.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - expat=2.6.3
  - importlib-metadata=8.5.0
  - ipykernel=6.29.5
  - ipython=8.28.0
  - jedi=0.19.1
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - krb5=1.21.3
  - ld_impl_linux-64=2.40
  - libedit=3.1.20230828
  - libffi=3.4.4
  - libgcc=14.1.0
  - libgcc-ng=14.1.0
  - libgomp=14.1.0
  - libsodium=1.0.20
  - libstdcxx=14.1.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - matplotlib-inline=0.1.7
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openssl=3.3.2
  - packaging=24.1
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.2
  - platformdirs=4.3.6
  - prompt-toolkit=3.0.48
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.18.0
  - python=3.12.7
  - python-dateutil=2.9.0
  - pyzmq=25.1.2
  - readline=8.2
  - setuptools=75.1.0
  - six=1.16.0
  - sqlite=3.45.3
  - stack_data=0.6.2
  - tk=8.6.14
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - wcwidth=0.2.13
  - wheel=0.44.0
  - xz=5.4.6
  - zeromq=4.3.5
  - zipp=3.20.2
  - zlib=1.2.13
  - pip:
      - annotated-types==0.7.0
      - anthropic==0.35.0
      - anyio==4.6.0
      - cachetools==5.5.0
      - certifi==2024.8.30
      - charset-normalizer==3.3.2
      - contourpy==1.3.0
      - cycler==0.12.1
      - distro==1.9.0
      - filelock==3.16.1
      - fonttools==4.54.1
      - fsspec==2024.9.0
      - google-ai-generativelanguage==0.6.10
      - google-api-core==2.20.0
      - google-api-python-client==2.147.0
      - google-auth==2.35.0
      - google-auth-httplib2==0.2.0
      - google-generativeai==0.8.2
      - googleapis-common-protos==1.65.0
      - grpcio==1.66.2
      - grpcio-status==1.66.2
      - h11==0.14.0
      - httpcore==1.0.6
      - httplib2==0.22.0
      - httpx==0.27.2
      - huggingface-hub==0.25.1
      - idna==3.10
      - jiter==0.5.0
      - kiwisolver==1.4.7
      - koalas==0.32.0
      - matplotlib==3.9.2
      - numpy==2.1.2
      - openai==1.51.1
      - pandas==2.2.3
      - pillow==10.4.0
      - proto-plus==1.24.0
      - protobuf==5.28.2
      - py4j==0.10.9.7
      - pyarrow==17.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - pyparsing==3.1.4
      - pypdf==5.0.1
      - pyspark==3.5.3
      - pytz==2024.2
      - pyyaml==6.0.2
      - requests==2.32.3
      - rsa==4.9
      - sniffio==1.3.1
      - tokenizers==0.20.0
      - tqdm==4.66.5
      - tzdata==2024.2
      - uritemplate==4.1.1
      - urllib3==2.2.3
